name: Docker Image CI

on:
  push:
    branches: [ "trunk" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.1
      - name: Unit Tests
        run: make test
      - name: Build
        run: CGO_ENABLED=0 GOOS=linux GOARCH=arm64 make build
      - name: LS
        run: ls -ltrsa
              
