name: Docker Image CI

on:
  push:
    branches: [ "trunk" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: ~/.cache/go-build ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1
      - name: Build
        run: CGO_ENABLED=0 GOOS=linux GOARCH=arm64 make build
      - name: LS
        run: ls bin -ltr
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          context: .
          file: build/docker/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/2dpoint-site:latest              
