name: Docker Image CI

on:
  push:
    branches: [ "trunk" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: ~/.cache/go-build ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1
      - name: Versioning
        id: version
        run: |
          go install github.com/audryus/lazyver@latest
          lazyver semver
          echo "output=$(cat .lazyver.yaml | head -n 1 | sed 's/version: //g' | tr -d '\n')" >> $GITHUB_OUTPUT
      - name: Unit Tests
        run: make test
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          context: .
          file: build/docker/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/2dpoint-site:${{steps.version.outputs.output}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          github-token: ${{ secrets.TOKEN }}           
